import { ArrowUpRight, ChartLineUp, Database, ChartBar, FileText, Code, DownloadSimple, LinkedinLogo, GithubLogo } from "@phosphor-icons/react";
const tools=[["Microsoft Excel","X","#217346"],["SQL (developing)","SQL","#17233d"],["Python (basic)","PY","#3776AB"],["Power BI (developing)","BI","#D99B00"]];
const projects=[["Provincial Product Accounts","GDP performance, industry growth and contributions","./projects.html"],["Statistical Data Processing","Validation, classification and reliable outputs","./projects.html"],["Economic Data Visualization","Dashboards, charts and statistical storytelling","./projects.html"]];
const socials=[{label:"LinkedIn",href:"https://www.linkedin.com/in/mariano-q-daga-ang-jr-566185286/",Icon:LinkedinLogo},{label:"GitHub",href:"https://github.com/marianodags",Icon:GithubLogo}];
export default function Hero(){return <section id="home" className="section-pad hero-dashboard"><div className="section-wrap"><div className="hero-topline"><div className="hero-intro"><div className="hero-identity"><img src="./mariano.jpg" alt="Portrait of Mariano Daga-ang" width="68" height="68" fetchPriority="high" decoding="async" className="hero-avatar"/><div><p className="kicker">Statistical Analyst · Data Analyst</p><p className="hero-location">Zamboanga del Norte, Philippines · Open to data opportunities</p></div></div><h1>Statistical Analyst · Data Analyst<br/><em>Turning data into clear decisions.</em></h1><p className="hero-summary">I’m Mariano, a Statistical Analyst and Computer Engineering graduate at the Philippine Statistics Authority. I work with official statistics, provincial economic analysis, establishment data, data quality validation, reporting, and data visualization.</p></div><div className="hero-actions" aria-label="Portfolio actions"><a href="./contact.html">Get in touch <ArrowUpRight size={17}/></a><a className="secondary" href="./projects.html">Explore work</a><a className="secondary" href="./resume.pdf" download="Mariano-Daga-ang-Resume.pdf"><DownloadSimple size={17}/> Download resume</a><a className="social-cta" href="#skills"><Code size={17}/> View skills</a>{socials.map(({label,href,Icon})=><a className="social-cta" key={label} href={href} target="_blank" rel="noopener noreferrer"><Icon size={17}/>{label}</a>)}</div></div>
<div className="tool-panel" role="region" aria-label="DAILY DRIVERS: Tools Mariano works with"><div className="tool-panel-label"><span>DAILY DRIVERS</span><strong>Tools I work with</strong></div><div className="marquee"><div className="marquee-track">{[0,1].map((copy)=><div className="marquee-group" key={copy} aria-hidden={copy === 1}>{tools.map(([name,mark,color])=><span className="tool-chip" key={name}><span className="tool-mark" style={{backgroundColor:color}}>{mark}</span>{name}</span>)}</div>)}</div></div></div>
<div className="dashboard-grid"><article className="dashboard-card project-feature"><h2><span className="card-icon"><FolderIcon/></span> Selected work</h2><p>Statistical work and data projects built around real-world questions.</p><div className="dashboard-list">{projects.map(([name,desc,href],i)=><a href={href} key={name}><span>{String(i+1).padStart(2,"0")} &nbsp; {name}<small className="block">{desc}</small></span><ArrowUpRight size={17}/></a>)}</div></article>
<article className="dashboard-card"><h2><span className="card-icon"><ChartLineUp size={20}/></span> Analytical focus</h2><p>Where statistical methods meet practical decisions.</p><div className="dashboard-list"><div className="row-item"><span>Official statistics &amp; data quality validation</span><small>01</small></div><div className="row-item"><span>Provincial GDP &amp; economic indicators</span><small>02</small></div><div className="row-item"><span>Statistical reporting &amp; visualization</span><small>03</small></div></div></article>
<article className="dashboard-card"><h2><span className="card-icon"><ChartBar size={20}/></span> How I add value</h2><p>Turning raw records into structured, interpretable outputs.</p><div className="metric-row"><div className="metric"><strong>Reliable</strong><span>Validated data</span></div><div className="metric"><strong>Clear</strong><span>Useful reporting</span></div></div><div className="mini-bars" aria-hidden="true">{[34,52,43,68,56,82,72,94,65,78,100,84].map((h,i)=><i key={i} style={{height:h+"%"}}/>)}</div></article>
<article className="dashboard-card"><h2><span className="card-icon"><Database size={20}/></span> My background</h2><p>Computer Engineering graduate applying technology and statistical thinking to official data and economic indicators.</p><div className="dashboard-list"><a href="./about.html"><span>More about Mariano</span><ArrowUpRight size={17}/></a></div></article>
<article className="dashboard-card"><h2><span className="card-icon"><FileText size={20}/></span> What I deliver</h2><p>Practical support from data preparation to final communication.</p><div className="dashboard-list"><a href="./services.html"><span>Statistical analysis</span><ArrowUpRight size={17}/></a><a href="./services.html"><span>Data visualization</span><ArrowUpRight size={17}/></a><a href="./services.html"><span>Reports & dashboards</span><ArrowUpRight size={17}/></a></div></article></div></div></section>}
function FolderIcon(){return <Code size={20}/>;}
