import React from "react";
import ReactDOM from "react-dom/client";
import Navbar from "./components/Navbar.jsx";
import Home from "./components/Home.jsx";
import Projects from "./components/Projects.jsx";
import Services from "./components/Services.jsx";
import About from "./components/About.jsx";
import Contact from "./components/Contact.jsx";
import "./index.css";
const pages={home:Home,projects:Projects,services:Services,about:About,contact:Contact};
const Content=pages[document.body.dataset.page||"home"]||Home;
ReactDOM.createRoot(document.getElementById("root")).render(<React.StrictMode><div className="min-h-screen text-[#111827]"><Navbar/><main className="lg:pl-[250px]"><Content/></main></div></React.StrictMode>);
